apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment
  namespace: lokid
spec:
  replicas: 3
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
        - name: busybox
          image: busybox:stable # Image from Docker Hub
          command: ["sleep", "infinity"] # Keep the container running
